### ISSUE TITLE
Organization of code

### ISSUE THREAD

**Issue by TomMaullin** [TomMaullin/RFTSim#1]
We should reorganize the code into something a bit more manageable. My suggestion is:

- RFTSim/
   - lib/ (for all small functions like expectedm etc)
   - preprocessing/ (for all data generation, spm functions etc)
   - fig/ (for all figure generation)
   - img/ (for any output images)
   - results/ (for any mat files from simulations)
   - buster/(for any buster scripts)
 
In the main folder we also need a `.gitignore`, a central script we can run to generate all figures and put them in the img file/folder and a `readme.md`.

What do you think of this layout @hallomotocar ?

**Comment by BrainStatsSam** [comment]
Looks good!

**Comment by TomMaullin** [comment]
This issue has now been resolved
